"""add_dark_sponsor_federation_streak

Revision ID: 0b7c15a2853f
Revises: add_investments_manual
Create Date: 2026-05-19 15:38:23.144834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7c15a2853f'
down_revision = 'add_investments_manual'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_sponsor_last_week_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('federation_loan_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('federation_loan_streak')
        batch_op.drop_column('dark_sponsor_last_week_id')

    # ### end Alembic commands ###
