"""add_scouting_enabled

Revision ID: 545d5ef334b8
Revises: 670afa43d25c
Create Date: 2026-05-17 18:46:55.719928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545d5ef334b8'
down_revision = '670afa43d25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('scouting_enabled')

    # ### end Alembic commands ###
