"""add_wellness_fields

Revision ID: 8021a58ceef7
Revises: 0b7c15a2853f
Create Date: 2026-05-19 17:51:06.787283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8021a58ceef7'
down_revision = '0b7c15a2853f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physio_sessions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('health_sessions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cyber_sessions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locker_last_grant_week_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('soccer_pro_end_week_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('soccer_future_end_week_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('soccer_future_skill_boosted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('soccer_future_skill_boosted')
        batch_op.drop_column('soccer_future_end_week_id')
        batch_op.drop_column('soccer_pro_end_week_id')
        batch_op.drop_column('locker_last_grant_week_id')
        batch_op.drop_column('cyber_sessions')
        batch_op.drop_column('health_sessions')
        batch_op.drop_column('physio_sessions')

    # ### end Alembic commands ###
